config/routes.rb
Rails.application.routes.draw do
  resources :portfolio_items
  get 'home/index'

  devise_for :users

  root 'home#index'

end

app/models/portfolio_item.rb
class PortfolioItem < ActiveRecord::Base

  mount_uploader :image, PortfolioItemImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]

  # GET /portfolio_items
  # GET /portfolio_items.json
  def index
    @portfolio_items = PortfolioItem.all
  end

  # GET /portfolio_items/1
  # GET /portfolio_items/1.json
  def show
  end

  # GET /portfolio_items/new
  def new
    @portfolio_item = PortfolioItem.new
  end

  # GET /portfolio_items/1/edit
  def edit
  end

  # POST /portfolio_items
  # POST /portfolio_items.json
  def create
    @portfolio_item = PortfolioItem.new(portfolio_item_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_items/1
  # PATCH/PUT /portfolio_items/1.json
  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_items/1
  # DELETE /portfolio_items/1.json
  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_items_url, notice: 'Portfolio item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_item
      @portfolio_item = PortfolioItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_item_params
      params.require(:portfolio_item).permit(:image, :caption, :description, :active, :order)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper
end

app/views/home/index.html.erb
<h1>My Portfolio</h1>
<p>I am an awesome coder...?</p>

<% if user_signed_in? %>


<%= link_to 'Add portfolio item', new_portfolio_item_path, class: 'btn btn-success' %>

</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %> </li>
        <% else %>
      <li> <%= link_to 'Sign in', new_user_session_path %> </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolioapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/portfolio_items/_form.html.erb
<%= simple_form_for(@portfolio_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :image %>
    <%= f.input :caption %>
    <%= f.input :description %>
    <%= f.input :active %>
    <%= f.input :order %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/portfolio_items/edit.html.erb
<h1>Editing Portfolio Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio_item %> |
<%= link_to 'Back', portfolio_items_path %>

app/views/portfolio_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Portfolio Items</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Image</th>
      <th>Caption</th>
      <th>Description</th>
      <th>Active</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio_items.each do |portfolio_item| %>
      <tr>
        <td><%= portfolio_item.image %></td>
        <td><%= portfolio_item.caption %></td>
        <td><%= portfolio_item.description %></td>
        <td><%= portfolio_item.active %></td>
        <td><%= portfolio_item.order %></td>
        <td><%= link_to 'Show', portfolio_item %></td>
        <td><%= link_to 'Edit', edit_portfolio_item_path(portfolio_item) %></td>
        <td><%= link_to 'Destroy', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio item', new_portfolio_item_path %>

app/views/portfolio_items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-body">

        <h1>New Portfolio Item</h1>

        <%= render 'form' %>

        <%= link_to 'Back', portfolio_items_path %>
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolio_items/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= image_tag @portfolio_item.image, class: 'img-rounded', width: '100%'%>
            <h4>
                <%= @portfolio_item.caption %>
            </h4>
            <p>
                <%= @portfolio_item.description %>
            </p>
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_portfolio_item_path(@portfolio_item) %>
              <%= link_to 'Back', new_portfolio_item_path %>
              <% else %>
              <%= link_to 'Back', new_portfolio_item_path %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

 |